version: "3.9"

services:
  pg:
    image: timescale/timescaledb-ha:pg17
    container_name: pg
    environment:
      POSTGRES_USER: POSTGRES
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weather
    ports:
      - "5432:5432"           # expose port 5432 on localhost
    volumes:
      - pgdata:/pgdata        # mount volume at pgdata

  app:
    image: weather
    container_name: zerogvt/weather
    ports:
      - "5000:5000"               # expose port 5000 on localhost
    depends_on:
      - pg
    
volumes:
  pgdata:
