"""empty message

Revision ID: 19b18eaaa583
Revises: 37c25317f0f6
Create Date: 2025-09-15 23:41:14.324422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b18eaaa583'
down_revision = '37c25317f0f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'station', ['station'], ['code'])
        batch_op.create_foreign_key(None, 'sensor', ['sensor_id'], ['id'])

    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_station_code'))
        batch_op.drop_constraint(batch_op.f('sensor_station_code_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'station', ['station_code'], ['code'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sensor_station_code_fkey'), 'station', ['station_code'], ['code'])
        batch_op.create_index(batch_op.f('ix_sensor_station_code'), ['station_code'], unique=False)

    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
