"""empty message

Revision ID: 1fbd77ec0ae9
Revises: 
Create Date: 2025-09-16 18:12:52.465823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fbd77ec0ae9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast',
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('temperature', sa.Integer(), nullable=False),
    sa.Column('humidity', sa.Integer(), nullable=False),
    sa.Column('wind', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('forecast_date', 'city')
    )
    op.create_table('station',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longtitude', sa.Float(), nullable=False),
    sa.Column('date_install', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    with op.batch_alter_table('station', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_station_city'), ['city'], unique=False)

    op.create_table('sensor',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('station_code', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['station_code'], ['station.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurement',
    sa.Column('measurement_id', sa.String(length=64), nullable=False),
    sa.Column('station', sa.String(length=64), nullable=False),
    sa.Column('sensor_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('measurement', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station'], ['station.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sensor_id', 'date')
    )
    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurement_station'), ['station'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurement_station'))

    op.drop_table('measurement')
    op.drop_table('sensor')
    with op.batch_alter_table('station', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_station_city'))

    op.drop_table('station')
    op.drop_table('forecast')
    # ### end Alembic commands ###
