"""empty message

Revision ID: 4e3c4c246e44
Revises: 
Create Date: 2025-09-15 11:28:22.492200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3c4c246e44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement',
    sa.Column('measurement_id', sa.String(length=64), nullable=False),
    sa.Column('station', sa.String(length=64), nullable=False),
    sa.Column('sensor_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('measurement', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('sensor_id', 'date')
    )
    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurement_sensor_id'), ['sensor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurement_station'), ['station'], unique=False)

    op.create_table('station',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longtitude', sa.Float(), nullable=False),
    sa.Column('date_install', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    with op.batch_alter_table('station', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_station_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_station_code'), ['code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_station_code'))
        batch_op.drop_index(batch_op.f('ix_station_city'))

    op.drop_table('station')
    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurement_station'))
        batch_op.drop_index(batch_op.f('ix_measurement_sensor_id'))

    op.drop_table('measurement')
    # ### end Alembic commands ###
