"""empty message

Revision ID: e2efac15af32
Revises: 
Create Date: 2025-09-14 21:30:49.816926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2efac15af32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement',
    sa.Column('measurement_id', sa.Uuid(), nullable=False),
    sa.Column('station', sa.String(length=64), nullable=False),
    sa.Column('sensor_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('measurement', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('measurement_id')
    )
    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurement_sensor_id'), ['sensor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurement_station'), ['station'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurement_station'))
        batch_op.drop_index(batch_op.f('ix_measurement_sensor_id'))

    op.drop_table('measurement')
    # ### end Alembic commands ###
